source 'https://rubygems.org'


gem 'rails', '~> 5.0.2'
gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'react-rails'
gem 'sprockets-coffee-react'
gem 'bootstrap-sass'
gem 'jquery-ui-rails'

gem 'jquery-rails'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'paperclip'
gem 'nested_form'
gem 'devise'
gem 'haml-rails'

gem 'railroady'

group :development, :test do
  gem 'pry-byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

